version: '3.7'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - KAFKA_BROKER=kafka:9092
      
      - AWS_REGION=ap-south-1
      - AWS_ACCESS_KEY_ID=AKIA6GBMHLZURGC5UMXN
      - AWS_SECRET_ACCESS_KEY=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
    depends_on:
      - kafka
    networks:
      - my-network
  kafka:
    image: wurstmeister/kafka:latest
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9092,OUTSIDE://localhost:9093
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9092,OUTSIDE://0.0.0.0:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENER_NAME: INSIDE
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
    networks:
      - my-network
  zookeeper:
    image: wurstmeister/zookeeper:latest
    ports:
      - "2181:2181"
    networks:
      - my-network
networks:
  my-network: